# @package _global_
method_name: genie2
dataset:
  cache_dir: ${hydra:runtime.cwd}/../preprocess/.cache/jsonl
  min_n_res: 0
  max_n_res: 256
  max_n_chain: 1

  motif_prob: 0.8
  motif_min_pct_res: 0.05
  motif_max_pct_res: 0.5
  motif_min_n_seg: 1
  motif_max_n_seg: 4

diffusion:
  n_timestep: 1000
  schedule: cosine

model:
  # General
  c_s: 384
  c_p: 128
  rescale: 1

  # Single feature network
  c_pos_emb: 256
  c_chain_emb: 64
  c_timestep_emb: 512

  # Pair feature network
  relpos_k: 32
  template_dist_min: 2
  template_dist_step: 0.5
  template_dist_n_bin: 37

  # Pair transform network
  n_pair_transform_layer: 5
  include_mul_update: True
  include_tri_att: False
  c_hidden_mul: 128
  c_hidden_tri_att: 32
  n_head_tri: 4
  tri_dropout: 0.25
  pair_transition_n: 4

  # Structure netowrk
  n_structure_layer: 8
  n_structure_block: 1
  c_hidden_ipa: 16
  n_head_ipa: 12
  n_qk_point: 4
  n_v_point: 8
  ipa_dropout: 0.1
  n_structure_transition_layer: 1
  structure_transition_dropout: 0.1

experiment:
  strategy: ddp
  use_distributed_sampler: True
  use_wandb: False

  seed: 100
  num_epoch: 5
  batch_size: 8
  log_every_n_step: 1000
  ckpt_freq: 10
  condition_loss_weight: 1
  lr: 0.0001
  lr_scheduler: null

inference:
  task_type: unconditional # scaffold

  unconditional:
    weights_path: ${hydra:runtime.cwd}/src/genie2/last.ckpt
    output_dir: ./genie2_outputs/
    num_samples: 5 # number of samples per task
    batch_size: 4 # number of tasks in a batch
    scale: 0.6 # Sampling noise scale
    max_length: 60
    min_length: 50
    length_step: 1

  scaffold:
    weights_path: ${hydra:runtime.cwd}/src/genie2/last.ckpt
    output_dir: ./genie2_outputs/
    num_samples: 10 # number of samples per task
    batch_size: 4 # number of tasks in a batch
    scale: 0.4 # Sampling noise scale
    strength: 0
    datadir: ${hydra:runtime.cwd}/src/genie2/design25








